Updating R CMD check Actions
poissonconsulting/shinyutils pull request #4
Opened 2021-11-10 15:32 UTC by MowahidLatif

Do not merge until checks passed.

2021-11-10 15:46 UTC, MowahidLatif commented
All checks have passed, please merge.

2021-11-11 23:40 UTC, aylapear requested changes
Please correct the badges, switch the R-CMD-check for the R build status

2021-11-12 20:32 UTC, MowahidLatif commented
Please merge this branch. Everything is in order.

2021-11-12 23:02 UTC, aylapear approved these changes

2021-11-12 23:02 UTC, merged